### ISSUE TITLE
Docker in Unraid

### ISSUE THREAD

**Issue by Njur** [TheUltimateC0der/alternatrr#3]
Can you get the docker to work with Unraid?
I can install it, but it won't start.

**Comment by TheUltimateC0der** [comment]
I have no idea what I need to change, in order to make it work on unRAID. I have nothing to test.

**Comment by Njur** [comment]
> I have no idea what I need to change, in order to make it work on unRAID. I have nothing to test.
Damn, hoped you knew:)

**Comment by TheUltimateC0der** [comment]
If you post the error messages, we can try to figure it out.

**Comment by Njur** [comment]
> If you post the error messages, we can try to figure it out.

Thanks:)

When I start the docker and go into the log it gives this:

text  error  warn  system  array  login  

Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'implementationInstance')
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton[TService](IServiceCollection services, TService implementationInstance)
   at alternatrr.Startup.ConfigureServices(IServiceCollection services) in /src/alternatrr/Startup.cs:line 30
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at alternatrr.Program.Main(String[] args) in /src/alternatrr/Program.cs:line 17
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'implementationInstance')
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton[TService](IServiceCollection services, TService implementationInstance)
   at alternatrr.Startup.ConfigureServices(IServiceCollection services) in /src/alternatrr/Startup.cs:line 30
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at alternatrr.Program.Main(String[] args) in /src/alternatrr/Program.cs:line 17

** Press ANY KEY to close this window **

**Comment by TheUltimateC0der** [comment]
Okay. That's an easy one. You simply forgot to provide the login details as shown in the Readme.md. You have to provide login details via environment variables to the application, so you can have a secure login. 

They Start with Login_

**Comment by Njur** [comment]
Thanks for the quick reply.
Problem is I don't know where the config file is located.
Normally they have their own docker container folder, but since it hasn't started the first time, no folder is created.
I will need to investigate, but thanks again for the quick help:)

**Comment by Njur** [comment]
The username and password is that the one I use for Sonarr and the port is that also the Sonarr port?

**Comment by TheUltimateC0der** [comment]
> ... Problem is I don't know where the config file is located. Normally they have their own docker container folder, but since it hasn't started the first time, no folder is created. I will need to investigate, but thanks again for the quick help:)

There is no config file. Everything is configured via environment variables. 

This looks promising: https://www.reddit.com/r/unRAID/comments/o4v9yt/unraid_docker_and_env_variables/

The environment variables for alternatrr are 

```
Login__Username=Test
Login__Password=ChangeMe321!
```

So it should be 

```
Config type: Variable
Key: Login__Username
Value: <Put your Username here>
```
and 
```
Config type: Variable
Key: Login__Password
Value: <Put your Password here>
```

**Comment by dhopson** [comment]
verified working in unraid (6.11.5), you just need to specify the variables and point to the correct path for sonarr/alternatrr

![image](https://user-images.githubusercontent.com/21068326/233410806-25abd448-01c7-4075-ad9c-22ef0ce9629b.png)

**Comment by Njur** [comment]
Yes, it actually works...
The docker started now.
Thanks for the help both of you and especially the screenshot was helpful!

**Comment by Njur** [comment]
Is there a wiki to change afterwards?
Do I just go in via. portnumber or do I change within Sonarr GUI?

**Comment by TheUltimateC0der** [comment]
> Is there a wiki to change afterwards?

What Wiki?

>Do I just go in via. portnumber or do I change within Sonarr GUI?

You dont have to change anything in the Sonarr GUI. 
If you want to reach the alternatrr UI, you have to take a look on what port has been exposed for this container.

**Comment by Njur** [comment]
@TheUltimateC0der Just wanted to follow up and say I got it working, so thank you for this great addon!
