### ISSUE TITLE
Docker  Error. An error occurred while processing your request.

### ISSUE THREAD

**Issue by CyronixJW** [TheUltimateC0der/alternatrr#7]
Hi i would like to know how to fix this error Error.
An error occurred while processing your request.
Request ID: 00-7dd6580d4cfb4b45aa29486c180d6405-a63159500c753f42-00
I think this is related to the sonarr db. My sonarr is installed natively on my windows pc docker is on a wsl ubuntu distro where i set the path of the db thru /mnt/c/programdata/sonarr

**Comment by Pheromir** [comment]
A little bit late, but did you actually use the github-package as the docker image or the one from dockerhub?
The one in dockerhub didn't receive the latest updates for sonarr v4, which caused the same error for me.

Using `ghcr.io/theultimatec0der/alternatrr:latest` as the image did it's job.

**Comment by mobamoba** [comment]
I'm having this same error and I used ghcr.io/theultimatec0der/alternatrr:latest.

**Comment by TheUltimateC0der** [comment]
I can't do anything with that request ID

I need either an explanation what you did to reproduce it, or the full error message from docker logs or portainer

**Comment by mobamoba** [comment]
My logs are filled with this. And it's what occurs the moment I login to Alternatrr:

fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: Series'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
         at alternatrr.Controllers.HomeController.Index() in /src/alternatrr/Controllers/HomeController.cs:line 29
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|8_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'alternatrr.Controllers.HomeController.Error (alternatrr)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[102]
      Route matched with {action = "Error", controller = "Home", page = "", area = ""}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Error() on controller alternatrr.Controllers.HomeController (alternatrr).
info: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[1]
      Executing ViewResult, running view Error.
info: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[4]
      Executed ViewResult - view Error executed in 3.7396ms.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[105]
      Executed action alternatrr.Controllers.HomeController.Error (alternatrr) in 4.4558ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'alternatrr.Controllers.HomeController.Error (alternatrr)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]

**Comment by TheUltimateC0der** [comment]
Are you using V4 ?

**Comment by mobamoba** [comment]
No I'm on Sonarr 3.

**Comment by raphtabe** [comment]
Hello, 

I'm having the same issue.
Error detailed in development mode: 
> A database operation failed while processing the request.
> SqliteException: SQLite Error 1: 'no such table: Series'

Idem with both images: 
    image: theultimatecoder/alternatrr:latest
    image: ghcr.io/theultimatec0der/alternatrr:latest

Sonarr version: 4.0.0.657

Thanks in advance.

**Comment by raphtabe** [comment]
A bit of context: 

My docker compose:

My setting:
I run sonarr & alternatrr on a sinology nas.
sonarr is installed from the package center
alternatrr is installed with docker

```
version: '3'
services:
  alternatrr:
    image: ghcr.io/theultimatec0der/alternatrr:latest
    environment:
    - ConnectionStrings__DefaultConnection=Data Source=/opt/alternatrr/app/alternatrr.db
    - ConnectionStrings__sonarr=Data Source=/opt/sonarr/app/sonarr.db
    - Login__Username=**********
    - Login__Password=***********
    volumes:
    - /volume1/@appdata/sonarr/.config/Sonarr:/opt/sonarr/app  #Mounting the directory with sonarr.db in it
    - /volume1/docker/alternatrr/app:/opt/alternatrr/app #Mounting the alternatrr.db peristent login
```

Here is the logs:



Request finished HTTP/1.1 GET http://192.168.0.10:8004/ - - - 500 - text/html;+charset=utf-8 19.1428ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
Executed endpoint 'alternatrr.Controllers.HomeController.Error (alternatrr)'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
Executed action alternatrr.Controllers.HomeController.Error (alternatrr) in 1.9001ms
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[105]
Executed ViewResult - view Error executed in 1.7406ms.
info: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[4]
Executing ViewResult, running view Error.
info: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[1]
Route matched with {action = "Error", controller = "Home", page = "", area = ""}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Error() on controller alternatrr.Controllers.HomeController (alternatrr).
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[102]
Executing endpoint 'alternatrr.Controllers.HomeController.Error (alternatrr)'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited\|8_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged\|17_1(ResourceInvoker invoker)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged\|17_1(ResourceInvoker invoker)
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited\|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
at alternatrr.Controllers.HomeController.Index() in /src/alternatrr/Controllers/HomeController.cs:line 29
at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: Series'.
An unhandled exception has occurred while executing the request.
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
Executed endpoint 'alternatrr.Controllers.HomeController.Index (alternatrr)'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
Executed action alternatrr.Controllers.HomeController.Index (alternatrr) in 3.1981ms
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[105]
at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: Series'.
at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: Series'.
An exception occurred while iterating over the results of a query for context type 'alternatrr.SonarrDbContext'.
fail: Microsoft.EntityFrameworkCore.Query[10100]
FROM "Series" AS "s"
SELECT "s"."Id", "s"."Actors", "s"."AddOptions", "s"."Added", "s"."AirTime", "s"."Certification", "s"."CleanTitle", "s"."FirstAired", "s"."Genres", "s"."Images", "s"."ImdbId", "s"."LastDiskSync", "s"."LastInfoSync", "s"."Monitored", "s"."Network", "s"."NextAiring", "s"."Overview", "s"."Path", "s"."QualityProfileId", "s"."Ratings", "s"."Runtime", "s"."SeasonFolder", "s"."Seasons", "s"."SeriesType", "s"."SortTitle", "s"."Status", "s"."Tags", "s"."Title", "s"."TitleSlug", "s"."TvMazeId", "s"."TvRageId", "s"."TvdbId", "s"."UseSceneNumbering", "s"."Year"
Failed executing DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
Route matched with {action = "Index", controller = "Home", page = "", area = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Index() on controller alternatrr.Controllers.HomeController (alternatrr).
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[102]
Executing endpoint 'alternatrr.Controllers.HomeController.Index (alternatrr)'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
Request starting HTTP/1.1 GET http://192.168.0.10:8004/ - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]

**Comment by raphtabe** [comment]
Ok, solved 🙂
version: '4' instead of 3...

**Comment by miquelalvarado** [comment]
Same issue here. I'm using Sonarr version 3.0.9.1549 and configuring alternatrr with the following docker compose:
```
# example docker-compose.yml

version: '3'
services:
  alternatrr:
    image: ghcr.io/theultimatec0der/alternatrr:latest
    environment:
    - TZ=Europe/Madrid
    - PGID=100
    - PUID=1000
    - ConnectionStrings__DefaultConnection=Data Source=/alternatrr/app/alternatrr.db
    - ConnectionStrings__sonarr=Data Source=/sonarr/sonarr.db
    - Login__Username=user
    - Login__Password=pass
    - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - 5000:80
    volumes:
    - /volume1/data/config:/sonarr  #Mounting the directory with sonarr.db in it
    - /volume1/data/config/alternatrr:/alternatrr/app #Mounting the alternatrr.db peristent login
```

and I'm getting the following error:
![Screenshot 2023-12-04 at 16 20 36](https://github.com/TheUltimateC0der/alternatrr/assets/3353597/9889c129-b442-40b0-afdc-1f0863e02c7e)

in the log:
```
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (12ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT "s"."Id", "s"."Actors", "s"."AddOptions", "s"."Added", "s"."AirTime", "s"."Certification", "s"."CleanTitle", "s"."FirstAired", "s"."Genres", "s"."Images", "s"."ImdbId", "s"."LanguageProfileId", "s"."LastDiskSync", "s"."LastInfoSync", "s"."Monitored", "s"."Network", "s"."NextAiring", "s"."Overview", "s"."Path", "s"."QualityProfileId", "s"."Ratings", "s"."Runtime", "s"."SeasonFolder", "s"."Seasons", "s"."SeriesType", "s"."SortTitle", "s"."Status", "s"."Tags", "s"."Title", "s"."TitleSlug", "s"."TvMazeId", "s"."TvRageId", "s"."TvdbId", "s"."UseSceneNumbering", "s"."Year"
      FROM "Series" AS "s"
fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'alternatrr.SonarrDbContext'.
      Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: Series'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
      Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: Series'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```

Not sure what I am doing wrong 😅

**Comment by harry71019** [comment]
> Ok, solved 🙂 version: '4' instead of 3...

Yep this is what worked for me with Synology and docker

**Comment by armdan** [comment]
> Same issue here. I'm using Sonarr version 3.0.9.1549 and configuring alternatrr with the following docker compose:
> 
> ```
> # example docker-compose.yml
> 
> version: '3'
> services:
>   alternatrr:
>     image: ghcr.io/theultimatec0der/alternatrr:latest
>     environment:
>     - TZ=Europe/Madrid
>     - PGID=100
>     - PUID=1000
>     - ConnectionStrings__DefaultConnection=Data Source=/alternatrr/app/alternatrr.db
>     - ConnectionStrings__sonarr=Data Source=/sonarr/sonarr.db
>     - Login__Username=user
>     - Login__Password=pass
>     - ASPNETCORE_ENVIRONMENT=Development
>     ports:
>     - 5000:80
>     volumes:
>     - /volume1/data/config:/sonarr  #Mounting the directory with sonarr.db in it
>     - /volume1/data/config/alternatrr:/alternatrr/app #Mounting the alternatrr.db peristent login
> ```
> 
> and I'm getting the following error: ![Screenshot 2023-12-04 at 16 20 36](https://private-user-images.githubusercontent.com/3353597/287745475-9889c129-b442-40b0-afdc-1f0863e02c7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwODQ4OTIsIm5iZiI6MTcxMTA4NDU5MiwicGF0aCI6Ii8zMzUzNTk3LzI4Nzc0NTQ3NS05ODg5YzEyOS1iNDQyLTQwYjAtYWZkYy0xZjA4NjNlMDJjN2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjJUMDUxNjMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWUwY2QyNmIxNDcwNmE3OWNhYjhjZWQzYjU0MDkwMmIxNjk5ODJmN2I2NDYwNDNlNzE2Njg2Y2RmMDI1OTQ5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jxCdDPqJFRG2C6llgMbqvtSKCReXVtrKJsSOwQvEtdA)
> 
> in the log:
> 
> ```
> fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
>       Failed executing DbCommand (12ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
>       SELECT "s"."Id", "s"."Actors", "s"."AddOptions", "s"."Added", "s"."AirTime", "s"."Certification", "s"."CleanTitle", "s"."FirstAired", "s"."Genres", "s"."Images", "s"."ImdbId", "s"."LanguageProfileId", "s"."LastDiskSync", "s"."LastInfoSync", "s"."Monitored", "s"."Network", "s"."NextAiring", "s"."Overview", "s"."Path", "s"."QualityProfileId", "s"."Ratings", "s"."Runtime", "s"."SeasonFolder", "s"."Seasons", "s"."SeriesType", "s"."SortTitle", "s"."Status", "s"."Tags", "s"."Title", "s"."TitleSlug", "s"."TvMazeId", "s"."TvRageId", "s"."TvdbId", "s"."UseSceneNumbering", "s"."Year"
>       FROM "Series" AS "s"
> fail: Microsoft.EntityFrameworkCore.Query[10100]
>       An exception occurred while iterating over the results of a query for context type 'alternatrr.SonarrDbContext'.
>       Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: Series'.
>          at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
>          at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
>          at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
>          at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
>          at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
>          at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
>          at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
>          at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
>          at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
>          at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
>          at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
>       Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: Series'.
>          at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
>          at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
>          at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
>          at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
>          at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
>          at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
>          at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
>          at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
>          at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
>          at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
>          at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
> ```
> 
> Not sure what I am doing wrong 😅

how did you fix this ?

**Comment by adrianmihalko** [comment]
So it works or not with Sonarr v4?!

**Comment by gitthangbaby** [comment]
It works with Sonarr 4.
After hours trying to make [Umlautadaptarr](https://github.com/PCJones/UmlautAdaptarr/) work, realized it doesn't work with torrents. Resumed work on Alternatrr, and after hours of docker set up, adding GHCR manually, it finally ran.
Notes:

- added mapping will disable all but last mappings because of "TooManyRequest" error. So only the last one can be searched.
- if an item is deleted, it will cause database corruption
- Both "Sonarr" and "Prowlarr" apply "weknowbetter", not only stubborn against title aliases, but also resetting all changes. If you do "update ScenarioMappings set SearchTerm='MYFRIKKINGSEARCH' where id=XX", Sonarr will reset it on second search. Default mapping can't be touched. You think to tweak Prowlarr search, but it will reset your changes to YML. Prowlarr needs to clone the indexer definition, and then you can apply "Replace" terms to fix the search term. But wait, Sonarr will ignore it anyway, they will send "fixed" search term to Prowlarr, removing special characters, diacritics. So in some cases, you really need another ScenarioMapping, via Alternattr, which will add its id. Just don't delete records, and keep backups nonstop.
Finally I can search for "Hell's Kitchen" by changing the name to "Hell Kitchen".
